# Generated by Django 2.2.7 on 2019-11-22 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice', models.CharField(max_length=10, null=True)),
                ('vender', models.CharField(max_length=10, null=True)),
                ('buyer', models.CharField(max_length=10, null=True)),
                ('bill_date', models.DateField(auto_now=True)),
                ('bill_items', models.TextField(null=True)),
                ('digitized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, null=True)),
                ('auth', models.CharField(choices=[('1', 'EndUser'), ('2', 'InterUser')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billId', to='bills.Bills')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.User')),
            ],
        ),
    ]
