# Generated by Django 2.2.7 on 2019-11-22 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='bill_path',
            field=models.FileField(null=True, upload_to='billparser/bill collection'),
        ),
        migrations.AddField(
            model_name='bills',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bills.User'),
        ),
        migrations.DeleteModel(
            name='BillRelation',
        ),
    ]
